<?php

// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'News\Module'                                     => __DIR__ . '/../../Module.php',
    'News\Controller\NewsController'                  => __DIR__ . '/../../src/News/Controller/NewsConroller.php',
   
);